version: '3.8'

services:
  hdbet:
    container_name: HD-BET
    hostname: HD-BET
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    # image: pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel
    tty: true
    stdin_open: true
    shm_size: 10g
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: 1
            # device_ids: ['0']
    volumes:
      - ${PWD}:/workspace
    # environment:
      # - CUDA_VISIBLE_DEVICES=0
    working_dir: /workspace
    entrypoint: python run.py
